datadir: /Users/dk/.poktroll
grpc_endpoint: localhost:9090
application_fund_goal: 100000000upokt
txflags: ""
txflagstemplate: {}
applications:
- name: relay_spam_app_0
  address: pokt18wmctmhu49csyy6j0eyhmua63rvlwgc8hddg2c
  mnemonic: certain monitor elephant guard must vacant magnet present bacon scare
    social cattle enact average stairs orient disorder whisper frame banner version
    open spray brother
  stakegoal: 0
  serviceidgoal: ""
  delegateesgoal: []
- name: relay_spam_app_1
  address: pokt15d23cx4xsntqspag4pmn2waf2qwqlhtcnwhc3r
  mnemonic: notice iron season hawk travel pioneer suggest say taste wave curtain
    shock code seminar sell march layer avoid include retreat shine note element course
  stakegoal: 0
  serviceidgoal: ""
  delegateesgoal: []