{
 "title": "Protocol / Application Logs",
 "tags": [ "application_logs" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Application Staking",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"poktrolld-validator\"} | json | method = `StakeApplication`"
    }
   ]
  },
  {
   "title": "Application Unstaking",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container=\"poktrolld-validator\"} | json | method = `UnstakeApplication`"
    }
   ]
  },
  {
   "title": "Gateway Delegation",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{container=\"poktrolld-validator\"} | json | method = `DelegateToGateway`"
    }
   ]
  },
  {
   "title": "Gateway Undelegation",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{container=\"poktrolld-validator\"} | json | method = `UndelegateFromGateway`"
    }
   ]
  }
 ]
}