{
 "title": "Protocol / Claim/Proof/Settlement Logs",
 "tags": [ "claim_proof_settlement_logs" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Claim Creation",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"poktrolld-validator\"} |= `CreateClaim`"
    }
   ]
  },
  {
   "title": "Proof Submission",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container=\"poktrolld-validator\"} |= `SubmitProof`"
    }
   ]
  },
  {
   "title": "Claim Settlement",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{container=\"poktrolld-validator\"} |= `SettleSessionAccounting`"
    }
   ]
  }
 ]
}