{
 "title": "Protocol / Insights and On-Chain data",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Full Node",
    "query": {
     "query": "label_values(cometbft_consensus_height,job)"
    }
   },
   {
    "name": "service_id",
    "label": "Service ID",
    "query": {
     "query": "label_values(poktroll_proof_requirements,service_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Block processing times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Begin Blocker Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(begin_blocker{job=\"$job\"}) by (module, quantile)",
     "legendFormat": "{{module}}: q{{quantile}}"
    },
    {
     "expr": "sum(begin_blocker_sum{job=\"$job\"}) by (module) / sum(begin_blocker_count{job=\"$job\"}) by (module)",
     "legendFormat": "{{module}}: avg"
    }
   ]
  },
  {
   "title": "End Blocker Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(end_blocker{job=\"$job\"}) by (module, quantile)",
     "legendFormat": "{{module}}: q{{quantile}}"
    },
    {
     "expr": "sum(end_blocker_sum{job=\"$job\"}) by (module) / sum(end_blocker_count{job=\"$job\"}) by (module)",
     "legendFormat": "{{module}}: avg"
    }
   ]
  },
  {
   "title": "CometBFT Consensus Block Interval",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(le) (increase(cometbft_consensus_block_interval_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proof Validation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(poktroll_proof_validation{job=\"$job\"}) by (quantile)",
     "legendFormat": " q{{quantile}}"
    },
    {
     "expr": "sum(poktroll_proof_validation_sum{job=\"$job\"}) / sum(poktroll_proof_validation_count{job=\"$job\"})",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Tokenomics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "EMA by ServiceID",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(poktroll_relay_ema{job=\"$job\",service_id=~\"$service_id\"}) by (service_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RelayMining difficulty by ServiceID",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "sum(poktroll_relay_mining_difficulty{job=\"$job\",service_id=~\"$service_id\"}) by (service_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "On-Chain Relays",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(poktroll_relays{job=\"$job\",service_id=~\"$service_id\"}[1m])) by (service_id, claim_proof_stage)",
     "legendFormat": "{{service_id}}-{{claim_proof_stage}}"
    }
   ]
  },
  {
   "title": "Compute Units",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(poktroll_compute_units{job=\"$job\",service_id=~\"$service_id\"}[1m])) by (service_id, claim_proof_stage)",
     "legendFormat": "{{service_id}}-{{claim_proof_stage}}"
    }
   ]
  },
  {
   "title": "Proof requirements",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(poktroll_proof_requirements{job=\"$job\",service_id=~\"$service_id\"}[1m])) by (service_id, reason)",
     "legendFormat": "{{service_id}}-{{reason}}"
    }
   ]
  },
  {
   "title": "Minted / Burned / Slashed Tokens",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(poktroll_minted_tokens{job=\"$job\"}[1m])) by (module)",
     "legendFormat": "minted by {{module}}"
    },
    {
     "expr": "sum(increase(poktroll_burned_tokens{job=\"$job\"}[1m])) by (module)",
     "legendFormat": "burned by {{module}}"
    },
    {
     "expr": "sum(increase(poktroll_slashed_tokens{job=\"$job\"}[1m])) by (module)",
     "legendFormat": "slashed by {{module}}"
    },
    {
     "expr": "sum(increase(poktroll_minted_tokens{job=\"$job\"}[1m])) - sum(increase(poktroll_burned_tokens{job=\"$job\"}[1m]))",
     "legendFormat": "Minted total (minus burned)"
    }
   ]
  },
  {
   "title": "Claims",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(poktroll_claims{job=\"$job\",service_id=~\"$service_id\"}[1m])) by (service_id, claim_proof_stage)",
     "legendFormat": "{{service_id}}-{{claim_proof_stage}}"
    }
   ]
  }
 ]
}