{
 "title": "Load Testing",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gateway Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{instance=~\"gateway\\\\d+\"} |= ``"
    }
   ]
  },
  {
   "title": "Relayminer Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{instance=~\"relayminer\\\\d+\"} |= ``"
    }
   ]
  },
  {
   "title": "Validator Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{container=\"poktrolld-validator\"} |= ``"
    }
   ]
  },
  { "title": "Relayminers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Relayminer 1 Relay Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum (relayminer_requests_total{pod=~\"^relayminer1.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relayminer 1 CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"^relayminer1.*\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{pod=~\"^relayminer1.*\", resource=\"cpu\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{pod=~\"^relayminer1.*\", resource=\"cpu\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relayminer 1 Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"^relayminer1.*\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=~\"^relayminer1.*\", resource=\"memory\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"^relayminer1.*\", resource=\"memory\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relayminer 2 Relay Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum (relayminer_requests_total{pod=~\"^relayminer2.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relayminer 2 CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"^relayminer2.*\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{pod=~\"^relayminer2.*\", resource=\"cpu\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{pod=~\"^relayminer2.*\", resource=\"cpu\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relayminer 2 Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"^relayminer2.*\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=~\"^relayminer2.*\", resource=\"memory\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"^relayminer2.*\", resource=\"memory\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relayminer 3 Relay Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum (relayminer_requests_total{pod=~\"^relayminer3.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relayminer 3 CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"^relayminer3.*\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{pod=~\"^relayminer3.*\", resource=\"cpu\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{pod=~\"^relayminer3.*\", resource=\"cpu\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relayminer 3 Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"^relayminer3.*\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=~\"^relayminer3.*\", resource=\"memory\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"^relayminer3.*\", resource=\"memory\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Gateways", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Gateway 1 Relay Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum (appgateserver_requests_total{pod=~\"^gateway1.*\"}) by (request_type, service_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway 1 Relay Rrrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 48 },
   "targets": [
    {
     "expr": "sum (appgateserver_errors_total{pod=~\"^gateway1.*\"}) by (request_type, service_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway 1 CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"^gateway1.*\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{pod=~\"^gateway1.*\", resource=\"cpu\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{pod=~\"^gateway1.*\", resource=\"cpu\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway 1 Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"^gateway1.*\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"^gateway1.*\", resource=\"memory\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=~\"^gateway1.*\", resource=\"memory\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway 2 Relay Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum (appgateserver_requests_total{pod=~\"^gateway2.*\"}) by (request_type, service_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway 2 Relay Rrrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 56 },
   "targets": [
    {
     "expr": "sum (appgateserver_errors_total{pod=~\"^gateway2.*\"}) by (request_type, service_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway 2 CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"^gateway2.*\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{pod=~\"^gateway2.*\", resource=\"cpu\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{pod=~\"^gateway2.*\", resource=\"cpu\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway 2 Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"^gateway2.*\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"^gateway2.*\", resource=\"memory\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=~\"^gateway2.*\", resource=\"memory\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway 3 Relay Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum (appgateserver_requests_total{pod=~\"^gateway3.*\"}) by (request_type, service_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway 3 Relay Rrrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
   "targets": [
    {
     "expr": "sum (appgateserver_errors_total{pod=~\"^gateway3.*\"}) by (request_type, service_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway 3 CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"^gateway3.*\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{pod=~\"^gateway3.*\", resource=\"cpu\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{pod=~\"^gateway3.*\", resource=\"cpu\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway 3 Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"^gateway3.*\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"^gateway3.*\", resource=\"memory\"}\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=~\"^gateway3.*\", resource=\"memory\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}