{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "claims total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(poktroll_claims{}[$__rate_interval])) by (claim_proof_stage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "claims by app",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(poktroll_claims{}[$__rate_interval])) by (app_addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "claims by supplier operator",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(poktroll_claims{}[$__rate_interval])) by (sup_op_addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "on-chain relays total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(poktroll_relays{}[$__rate_interval])) by (claim_proof_stage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "relays by app (on-chain data)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(poktroll_relays{}[$__rate_interval])) by (app_addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "relays by supplier operator (on-chain data)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(poktroll_relays{}[$__rate_interval])) by (sup_op_addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application count in claims",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(poktroll_claims[1m])) by (claim_proof_stage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokenomics End Blocker Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(end_blocker{module=\"tokenomics\"}) by (module, quantile)",
     "legendFormat": "{{module}}: q{{quantile}}"
    },
    {
     "expr": "sum(end_blocker_sum{module=\"tokenomics\"}) by (module) / sum(end_blocker_count{module=\"tokenomics\"}) by (module)",
     "legendFormat": "{{module}}: avg"
    }
   ]
  },
  {
   "title": "Proof Validation Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(poktroll_proof_validation{}) by (quantile)",
     "legendFormat": " q{{quantile}}"
    },
    {
     "expr": "sum(poktroll_proof_validation_sum{}) / sum(poktroll_proof_validation_count{})",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}