{
 "title": "Protocol / Tokenomics / Relays life-cycle",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "group_by", "label": "Group by time / Window", "query": "1m,5m,10m,15m" }
  ]
 },
 "panels": [
  {
   "title": "Wht is this dashboard?",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 0 },
   "options": {
    "content": "## What does this dashboard show?\n\nAs relays flow through the network\nAppGate -> RelayMiner and RelayMiner creates proofs and claims, we can capture the whole relay cycle.\n\n1. shows the actual amount of relays on AppGate;\n2. shows the actual amount of relays processed by RelayMiner;\n3. the amount of relays from the onchain information using `EventClaimCreated`;\n4. relays from `EventProofSubmitted`;"
   }
  },
  {
   "title": "Actual AppGate Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(appgateserver_relay_requests_total[$group_by])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actual RelayMIner Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(relayminer_requests_total[$group_by])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relays (from onchain claims)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(b.\"timestamp\", '$group_by') AS time,\n    SUM(trim(both '\"' from ea_num_relays.value)::bigint) AS total_num_relays,\n    (ea_claim.value::json ->> 'supplier_operator_address') AS supplier_operator_address,\n    (ea_claim.value::json -> 'session_header' ->> 'service_id') AS service_id\nFROM\n    localnet.events e\nJOIN\n    localnet.event_attributes ea_num_relays ON ea_num_relays.event_id = e.id\n    AND ea_num_relays.key = 'num_relays'\nJOIN\n    localnet.event_attributes ea_claim ON ea_claim.event_id = e.id\n    AND ea_claim.key = 'claim'\nJOIN\n    localnet.blocks b ON b.id = e.block_id\nWHERE\n    e.type = 'pocket.proof.EventClaimCreated'\n    AND b.\"timestamp\" BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY\n    time, supplier_operator_address, service_id\nORDER BY\n    time;\n"
    }
   ]
  },
  {
   "title": "Relays (from onchain proofs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(b.\"timestamp\", '$group_by') AS time,\n    SUM(trim(both '\"' from ea_num_relays.value)::bigint) AS total_num_relays,\n    (ea_proof.value::json ->> 'supplier_operator_address') AS supplier_operator_address,\n    (ea_proof.value::json -> 'session_header' ->> 'service_id') AS service_id\nFROM\n    localnet.events e\nJOIN\n    localnet.event_attributes ea_num_relays ON ea_num_relays.event_id = e.id\n    AND ea_num_relays.key = 'num_relays'\nJOIN\n    localnet.event_attributes ea_proof ON ea_proof.event_id = e.id\n    AND ea_proof.key = 'proof'\nJOIN\n    localnet.blocks b ON b.id = e.block_id\nWHERE\n    e.type = 'pocket.proof.EventProofSubmitted'\n    AND b.\"timestamp\" BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY\n    time, supplier_operator_address, service_id\nORDER BY\n    time;\n"
    }
   ]
  }
 ]
}