# When `devnet-test-e2e` is added, also assign `devnet` and `push-image` to the PR.
devnet-test-e2e:
  prs:
    comment: |
      Run:
      ```bash
      make localnet_up
      make acc_initialize_pubkeys
      make test_e2e
      # Insert a screenshot
      ```

    label:
      - devnet
      - push-image

# When `devnet-test-e2e` is removed, also delete `devnet` from the PR.
-devnet-test-e2e:
  prs:
    unlabel:
      - devnet

# When `devnet` is added, also assign `push-image` to the PR.
devnet:
  prs:
    label:
      - push-image

# When `devnet` is removed, also delete `devnet-test-e2e` from the PR.
-devnet:
  prs:
    unlabel:
      - devnet-test-e2e

# Let the developer know that they need to push another commit after attaching the label to PR.
push-image:
  prs:
    comment: |
      The image is going to be pushed after the next commit.

      You can use `make trigger_ci` to push an empty commit.

      If you also want to run E2E tests, please add `devnet-test-e2e` label.

# When `push-image` is removed, also delete `devnet` from the PR.
-push-image:
  prs:
    unlabel:
      - devnet
      - devnet-test-e2e
