# When `devnet-e2e-test` is added, also assign `devnet` to the PR.
devnet-e2e-test:
  prs:
    label:
      - devnet

# When `devnet-e2e-test` is removed, also delete `devnet` from the PR.
-devnet-e2e-test:
  prs:
    unlabel:
      - devnet

# When `devnet` is added, also assign `push-image` to the PR.
devnet:
  prs:
    label:
      - push-image

# When `devnet` is removed, also delete `push-image` from the PR.
-devnet:
  prs:
    unlabel:
      - push-image
      - devnet-e2e-test

# Let the developer know that they need to push another commit after attaching the label to PR.
push-image:
  comment: The image is going to be pushed after the next commit. If you want to run an e2e test, it is necessary to push another commit.

# When `push-image` is removed, also delete `devnet` from the PR.
-push-image:
  prs:
    unlabel:
    - devnet
