# When `devnet-test-e2e` is added, also assign `devnet` and `push-image` to the PR.
devnet-test-e2e:
  prs:
    comment: The CI will now also run the e2e tests on devnet, which increases the time it takes to complete all CI checks. If you just created a pull request, you might need to push another commit to produce a container image DevNet can utilize to spin up infrastructure. You can use `make trigger_ci` to push an empty commit.
    label:
      - devnet
      - push-image

# When `devnet-test-e2e` is removed, also delete `devnet` from the PR.
-devnet-test-e2e:
  prs:
    unlabel:
      - devnet

# When `devnet` is added, also assign `push-image` to the PR.
devnet:
  prs:
    label:
      - push-image

# When `devnet` is removed, also delete `devnet-test-e2e` from the PR.
-devnet:
  prs:
    unlabel:
      - devnet-test-e2e

# Let the developer know that they need to push another commit after attaching the label to PR.
push-image:
  prs:
    comment: The image is going to be pushed after the next commit. You can use `make trigger_ci` to push an empty commit. If you also want to run an E2E test, please add `devnet-test-e2e` label.

# When `push-image` is removed, also delete `devnet` from the PR.
-push-image:
  prs:
    unlabel:
      - devnet
      - devnet-test-e2e
