version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    govet:
      enable:
        - shadow
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - revive
        path: ^x/.+/module\.go$
      - linters:
          - unused
        path: ^x/.+/cli/tx\.go$
      - linters:
          - revive
        path: .*/simulation/.*|_simulation\.go$
      - linters:
          - revive
        path: ^x/.+/codec.go$
      - linters:
          - errcheck
        path: _test\.go$
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - ^x/.+/genesis\.go$
