owner_address: pokt1g3suh4d0n3karude97zv2fllxhsaapm0zvl3fr
operator_address: pokt1g3suh4d0n3karude97zv2fllxhsaapm0zvl3fr
default_rev_share_percent:
  pokt1uag2wt3dey02g9um0yd525skjwelhcnrv5cyz6: 100
services:
  - service_id: anvil
    endpoints:
      - publicly_exposed_url: http://relayminer1:8545
        rpc_type: JSON_RPC
