# This Dockerfile is used to build container image for development purposes.
# It intentionally contains no security features, ships with code and troubleshooting tools.

FROM golang:1.23.0 as base

RUN apt update && \
    apt-get install -y \
    ca-certificates net-tools kubernetes-client \
    curl jq yq make vim less dnsutils

# enable faster module downloading.
ENV GOPROXY https://proxy.golang.org

COPY . /pocket

WORKDIR /pocket

RUN mv /pocket/bin/ignite /usr/bin/ && mv /pocket/bin/pocketd /usr/bin/

# Install Cosmovisor
RUN make install_cosmovisor

# These are helpful for testing locally:
# RUN mv bin/pocketd /usr/bin/
# RUN mv bin/ignite /usr/bin/

RUN make localnet_regenesis

# TODO_DOCUMENT(@okdas): Ports are not documented as they will soon be changed with a document to follow
EXPOSE 8545
EXPOSE 8546
EXPOSE 8547

ENTRYPOINT ["pocketd"]
