# This Dockerfile is used to build container image for development purposes.
# It intentionally contains no security features, ships with code and troubleshooting tools.

FROM golang:1.22.2 as base

RUN apt update && \
    apt-get install -y \
    ca-certificates net-tools kubernetes-client \
    curl jq make vim less dnsutils

# enable faster module downloading.
ENV GOPROXY https://proxy.golang.org

COPY . /poktroll

WORKDIR /poktroll

RUN mv /poktroll/bin/ignite /usr/bin/ && mv /poktroll/bin/poktrolld /usr/bin/

RUN ignite chain init --skip-proto

# TODO_TECHDEBT(@okdas): Ports are not documented as they will soon be changed with a document to follow
EXPOSE 8545
EXPOSE 8546
EXPOSE 8547

ENTRYPOINT ["poktrolld"]
