apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: host-proxy
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end }}
  selector:
    app: host-proxy