apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  namespace: ${NAMESPACE}
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        pokt.network/purpose: e2e-tests
    spec:
      containers:
        - name: e2e-tests
          image: ghcr.io/pokt-network/poktrolld:${IMAGE_TAG}
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              poktrolld q gateway list-gateway --node=$POCKET_NODE && \
              poktrolld q application list-application --node=$POCKET_NODE && \
              poktrolld q supplier list-supplier --node=$POCKET_NODE && \
              make acc_initialize_pubkeys && \
              go test -v ./e2e/tests/... -tags=e2e
          env:
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: auth_token
                  name: celestia-secret
            - name: POCKET_NODE
              value: tcp://${NAMESPACE}-sequencer:36657
            - name: SEQUENCER_RPC_ENDPOINT
              value: ${NAMESPACE}-sequencer:36657
            - name: E2E_DEBUG_OUTPUT
              value: "false" # Flip to true to see the command and result of the execution
            - name: POKTROLLD_HOME
              value: /root/.pocket
            - name: CELESTIA_HOSTNAME
              value: celestia-rollkit
            - name: APPGATE_SERVER_URL
              value: http://${NAMESPACE}-appgate-server:80
          volumeMounts:
            - mountPath: /root/.pocket/keyring-test/
              name: keys-volume
            - mountPath: /root/.pocket/config/
              name: configs-volume
      restartPolicy: Never
      volumes:
        - configMap:
            defaultMode: 420
            name: keys-${IMAGE_TAG}
          name: keys-volume
        - configMap:
            defaultMode: 420
            name: configs-${IMAGE_TAG}
          name: configs-volume
      serviceAccountName: default
  backoffLimit: 0
