apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  namespace: ${NAMESPACE}
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        pokt.network/purpose: e2e-tests
    spec:
      initContainers:
        # We need to ensure services like Validator, RelayMiner, PATH, etc. work
        # before executing an e2e test.
        - name: check-services
          image: ruby:3.0
          command: ["ruby"]
          args:
            # For reference, the script is located here:
            # https://github.com/pokt-network/protocol-infra/blob/main/charts/full-network/templates/ConfigMap-e2e-tests-script.yaml#L4
            - /e2e-script/check_services.rb
            - ${NAMESPACE}
          volumeMounts:
            - mountPath: /e2e-script/
              name: e2e-tests-check-services-script
      containers:
        - name: e2e-tests
          image: ghcr.io/pokt-network/pocketd:${IMAGE_TAG}
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              # Copy files from the secret to the writable directory
              cp -Lr /tmp/keys/* /root/.pocket/keyring-test/ && \
              echo "Listing /root/.pocket/keyring-test/ after copying:"
              ls -l /root/.pocket/keyring-test/ && \
              pocketd q gateway list-gateway --node=$POCKET_NODE && \
              pocketd q application list-application --node=$POCKET_NODE && \
              pocketd q supplier list-suppliers --node=$POCKET_NODE && \
              make acc_initialize_pubkeys && \
              go test -v ./e2e/tests/... -tags=e2e
          env:
            - name: POCKET_NODE
              value: tcp://${NAMESPACE}-validator-pocketd:26657
            - name: VALIDATOR_RPC_ENDPOINT
              value: ${NAMESPACE}-validator-pocketd:26657
            - name: E2E_DEBUG_OUTPUT
              value: "false" # Flip to true to see the command and result of the execution
            - name: POCKETD_HOME
              value: /root/.pocket
            - name: PATH_URL
              value: http://${NAMESPACE}-path:3069/v1
              # PATH relies on subdomains to get the requested service but our DevNet infra is not
              # built to expose arbitrary subdomains and supporting it would be a significant effort.
              # As a workaround, PATH_HOST_OVERRIDE is used as the host:port to connect to PATH while
              # the subdomain is passed as a Host header in the request.
            - name: PATH_HOST_OVERRIDE
              value: ${NAMESPACE}-path:3069
          volumeMounts:
            - mountPath: /root/.pocket/keyring-test/
              name: writable-keys-volume
            - mountPath: /root/.pocket/config/
              name: configs-volume
            - mountPath: /tmp/keys
              name: non-writable-keys-volume
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: writable-keys-volume
          emptyDir: {}
        - name: non-writable-keys-volume
          secret:
            secretName: keys-${IMAGE_TAG}
        - name: configs-volume
          configMap:
            name: configs-${IMAGE_TAG}
        - name: e2e-tests-check-services-script
          configMap:
            name: e2e-tests-check-services-script
      serviceAccountName: default
  backoffLimit: 0
