apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
  namespace: ${NAMESPACE}
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        pokt.network/purpose: e2e-tests
    spec:
      initContainers:
        - name: check-services
          image: curlimages/curl:8.8.0
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              check_http_status() {
                local endpoint=$1
                local max_retries=30
                local retries=0

                while :; do
                  echo "Checking HTTP status for the endpoint ${endpoint} (Attempt $((retries+1))/$max_retries)..."
                  HTTP_STATUS=$(curl -s -o /dev/null -w '%{http_code}' http://${endpoint})
                  if [[ "${HTTP_STATUS}" -eq 200 ]]; then
                    echo "HTTP request to ${endpoint} returned 200 OK."
                    break
                  else
                    echo "HTTP request to ${endpoint} did not return 200 OK. Status code: ${HTTP_STATUS}. Retrying in 10 seconds..."
                    retries=$((retries + 1))
                    if [[ ${retries} -ge ${max_retries} ]]; then
                      echo "Max retries reached for ${endpoint}. Exiting."
                      exit 1
                    fi
                    sleep 10
                  fi
                done
              }

              check_http_status "${NAMESPACE}-validator-poktrolld:36657"
              check_http_status "${NAMESPACE}-appgate-server:80"
              check_http_status "${NAMESPACE}-gateway:80"
              check_http_status "${NAMESPACE}-relayminer:8545"
      containers:
        - name: e2e-tests
          image: ghcr.io/pokt-network/poktrolld:${IMAGE_TAG}
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              # Copy files from the secret to the writable directory
              cp -Lr /tmp/keys/* /root/.poktroll/keyring-test/ && \
              echo "Listing /root/.poktroll/keyring-test/ after copying:"
              ls -l /root/.poktroll/keyring-test/ && \
              poktrolld q gateway list-gateway --node=$POCKET_NODE && \
              poktrolld q application list-application --node=$POCKET_NODE && \
              poktrolld q supplier list-supplier --node=$POCKET_NODE && \
              make acc_initialize_pubkeys && \
              go test -v ./e2e/tests/... -tags=e2e
          env:
            - name: POCKET_NODE
              value: tcp://${NAMESPACE}-validator-poktrolld:36657
            - name: VALIDATOR_RPC_ENDPOINT
              value: ${NAMESPACE}-validator-poktrolld:36657
            - name: E2E_DEBUG_OUTPUT
              value: "false" # Flip to true to see the command and result of the execution
            - name: POKTROLLD_HOME
              value: /root/.poktroll
            - name: APPGATE_SERVER_URL
              value: http://${NAMESPACE}-appgate-server:80
            - name: GATEWAY_URL
              value: http://${NAMESPACE}-gateway:80
          volumeMounts:
            - mountPath: /root/.poktroll/keyring-test/
              name: writable-keys-volume
            - mountPath: /root/.poktroll/config/
              name: configs-volume
            - mountPath: /tmp/keys
              name: non-writable-keys-volume
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: writable-keys-volume
          emptyDir: {}
        - name: non-writable-keys-volume
          secret:
            secretName: keys-${IMAGE_TAG}
        - configMap:
            defaultMode: 420
            name: configs-${IMAGE_TAG}
          name: configs-volume
      serviceAccountName: default
  backoffLimit: 0
