query_node_rpc_url: tcp://localhost:26657
query_node_grpc_url: tcp://localhost:9090
signing_key: app1
self_signing: true
listening_endpoint: http://0.0.0.0:42069
metrics:
  enabled: true
  addr: :9090
pprof:
  enabled: true
  addr: localhost:6060
