owner_address: pokt1re27pw4llwnatx4sq7rlggqzcm6j3f39epq2wa
operator_address: pokt1re27pw4llwnatx4sq7rlggqzcm6j3f39epq2wa
stake_amount: 1000070upokt
services:
  - service_id: anvil
    endpoints:
      - publicly_exposed_url: http://relayminer2:8545
        rpc_type: JSON_RPC
  - service_id: ollama
    endpoints:
      - publicly_exposed_url: http://relayminer2:8545
        rpc_type: REST
