// Generated by Ignite ignite.com/cli

import { SigningStargateClient, DeliverTxResponse, StdFee } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdateParams } from "./types/pocket/gateway/tx";
import { MsgStakeGateway } from "./types/pocket/gateway/tx";
import { MsgUnstakeGateway } from "./types/pocket/gateway/tx";
import { MsgUpdateParam } from "./types/pocket/gateway/tx";

import { EventGatewayStaked as typeEventGatewayStaked} from "./types"
import { EventGatewayUnbondingBegin as typeEventGatewayUnbondingBegin} from "./types"
import { EventGatewayUnbondingEnd as typeEventGatewayUnbondingEnd} from "./types"
import { EventGatewayUnbondingCanceled as typeEventGatewayUnbondingCanceled} from "./types"
import { Params as typeParams} from "./types"
import { Gateway as typeGateway} from "./types"

export { MsgUpdateParams, MsgStakeGateway, MsgUnstakeGateway, MsgUpdateParam };

type sendMsgUpdateParamsParams = {
  value: MsgUpdateParams,
  fee?: StdFee,
  memo?: string
};

type sendMsgStakeGatewayParams = {
  value: MsgStakeGateway,
  fee?: StdFee,
  memo?: string
};

type sendMsgUnstakeGatewayParams = {
  value: MsgUnstakeGateway,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateParamParams = {
  value: MsgUpdateParam,
  fee?: StdFee,
  memo?: string
};


type msgUpdateParamsParams = {
  value: MsgUpdateParams,
};

type msgStakeGatewayParams = {
  value: MsgStakeGateway,
};

type msgUnstakeGatewayParams = {
  value: MsgUnstakeGateway,
};

type msgUpdateParamParams = {
  value: MsgUpdateParam,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgUpdateParams({ value, fee, memo }: sendMsgUpdateParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgStakeGateway({ value, fee, memo }: sendMsgStakeGatewayParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgStakeGateway: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgStakeGateway({ value: MsgStakeGateway.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgStakeGateway: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUnstakeGateway({ value, fee, memo }: sendMsgUnstakeGatewayParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUnstakeGateway: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUnstakeGateway({ value: MsgUnstakeGateway.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUnstakeGateway: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateParam({ value, fee, memo }: sendMsgUpdateParamParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParam: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParam({ value: MsgUpdateParam.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParam: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgUpdateParams({ value }: msgUpdateParamsParams): EncodeObject {
			try {
				return { typeUrl: "/pocket.gateway.MsgUpdateParams", value: MsgUpdateParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message)
			}
		},
		
		msgStakeGateway({ value }: msgStakeGatewayParams): EncodeObject {
			try {
				return { typeUrl: "/pocket.gateway.MsgStakeGateway", value: MsgStakeGateway.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgStakeGateway: Could not create message: ' + e.message)
			}
		},
		
		msgUnstakeGateway({ value }: msgUnstakeGatewayParams): EncodeObject {
			try {
				return { typeUrl: "/pocket.gateway.MsgUnstakeGateway", value: MsgUnstakeGateway.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUnstakeGateway: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateParam({ value }: msgUpdateParamParams): EncodeObject {
			try {
				return { typeUrl: "/pocket.gateway.MsgUpdateParam", value: MsgUpdateParam.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParam: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						EventGatewayStaked: getStructure(typeEventGatewayStaked.fromPartial({})),
						EventGatewayUnbondingBegin: getStructure(typeEventGatewayUnbondingBegin.fromPartial({})),
						EventGatewayUnbondingEnd: getStructure(typeEventGatewayUnbondingEnd.fromPartial({})),
						EventGatewayUnbondingCanceled: getStructure(typeEventGatewayUnbondingCanceled.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						Gateway: getStructure(typeGateway.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const IgntModule = (test: IgniteClient) => {
	return {
		module: {
			PocketGateway: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default IgntModule;