# This Dockerfile exists to ensure Ignite OpenAPI works on all platforms.
# It is run by the make target `make ignite_openapi_gen` which outputs to `docs/static/openapi.yml`
FROM golang:1.23.5

# Install Ignite CLI
RUN curl https://get.ignite.com/cli\! | bash

WORKDIR /workspace

# Generate the OpenAPI spec and output to docs/static/openapi.yam
CMD ["ignite", "generate", "openapi", "--yes"]
