apiVersion: v1
kind: Service
metadata:
  name: celestia-rollkit
spec:
  selector:
    app: celestia-rollkit
  ports:
    - protocol: TCP
      name: core-rpc
      port: 26657
      targetPort: 26657
    - protocol: TCP
      name: rpc
      port: 26658
      targetPort: 26658
    - protocol: TCP
      name: gateway
      port: 26659
      targetPort: 26659
    - protocol: TCP
      name: grpc-da
      port: 26650
      targetPort: 26650
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celestia-rollkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celestia-rollkit
  template:
    metadata:
      labels:
        app: celestia-rollkit
    spec:
      serviceAccountName: celestia-rollkit
      # TODO: Add resource limits
      containers:
        - name: celestia
          image: ghcr.io/rollkit/local-celestia-devnet:v0.12.7
          ports:
            # https://github.com/rollkit/local-celestia-devnet?tab=readme-ov-file#exposed-ports
            - containerPort: 26657
            - containerPort: 26658
            - containerPort: 26659
            - containerPort: 26650
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: celestia-rollkit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-binding
subjects:
  - kind: ServiceAccount
    name: celestia-rollkit
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
