shannon_config:
  full_node_config:
    rpc_url: tcp://validator-pocket-validator:26657
    grpc_config:
      host_port: validator-pocket-validator:9090
      insecure: true
    lazy_mode: true
  gateway_config:
    gateway_mode: delegated
    gateway_address: pokt15vzxjqklzjtlz7lahe8z2dfe9nm5vxwwmscne4 # gateway1
    gateway_private_key_hex: cf09805c952fa999e9a63a9f434147b0a5abfd10f268879694c6b5a70e1ae177

services:
  anvil:
    alias: anvil
