shannon_config:
  full_node_config:
    rpc_url: tcp://validator-poktroll-validator:26657
    grpc_config:
      host_port: validator-poktroll-validator:9090
      insecure: true
    lazy_mode: true
  gateway_config:
    gateway_mode: delegated
    gateway_address: pokt15w3fhfyc0lttv7r585e2ncpf6t2kl9uh8rsnyz # gateway2
    gateway_private_key_hex: 177ba43cec962ea407f71da9c3994ba685708e82d5d7a6d7da3268e74119bf88

services:
  anvil:
    alias: anvil
