---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: path-gateway{actor_number}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: path-gateway{actor_number}
  template:
    metadata:
      labels:
        app: path-gateway{actor_number}
    spec:
      containers:
        - name: path-gateway
          image: path-gateway-local:latest # Local image tag
          imagePullPolicy: Never # Ensure Kubernetes uses local image
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: path-config{actor_number}
              mountPath: /app/.config.yaml
              subPath: .config.yaml
      volumes:
        - name: path-config{actor_number}
          configMap:
            name: path-config{actor_number}
            items:
              - key: path-config-{actor_number}.yaml
                path: .config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: path-gateway{actor_number}
spec:
  selector:
    app: path-gateway{actor_number}
  ports:
    - protocol: TCP
      name: rpc
      port: {port}
      targetPort: 3000
