---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pocketd-relayer-scripts
data:
  pocket.sh: |-
    #!/bin/sh

    ls -la /root/.pocket/config-src/
    mkdir -p /root/.pocket/config/
    cp -r -L /root/.pocket/config-src/* /root/.pocket/config/
    ls -la /root/.pocket/config/

    # sleep 99999

    # You can attach to this process with delve (dlv) for debugging purpose with `dlv attach $(pgrep pocketd) --listen :40005 --headless --api-version=2 --accept-multiclient` - run inside the container!
    pocketd relayer --node pocketd:36657 --signing-key servicer1 --keyring-backend test

    # OR debug the node (uncomment this line but comment previous line)
    # dlv exec --listen :40005 /usr/local/bin/pocketd relayer --pocket-node pocketd:36657 --sequencer-node pocketd:36657 --signing-key servicer1 --keyring-backend test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketd-relayer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocketd-relayer
  template:
    metadata:
      labels:
        app: pocketd-relayer
    spec:
      # TODO: Add resource limits
      containers:
        - name: pocketd
          image: pocketd
          # To allow Delve to do the thing
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add: ["SYS_PTRACE"]
          env:
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: celestia-secret
                  key: auth_token
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - containerPort: 40005
          command: ["/bin/sh"]
          args: ["/scripts/pocket.sh"]
          volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
            - name: keys-volume
              mountPath: /root/.pocket/keyring-test/
            - name: configs-volume
              mountPath: /root/.pocket/config-src/
      volumes:
        - name: scripts-volume
          configMap:
            name: pocketd-relayer-scripts
        - name: keys-volume
          configMap:
            name: pocketd-keys
        - name: configs-volume
          configMap:
            name: pocketd-configs
