config:
  pocket:
    query_node_rpc_url: tcp://sequencer-poktroll-sequencer:36657
    query_node_grpc_url: tcp://sequencer-poktroll-sequencer:36658
    tx_node_grpc_url: tcp://sequencer-poktroll-sequencer:36658

  signing_key_name: supplier1
  smt_store_path: smt_stores

  proxies:
    - name: http-proxy
      type: http
      host: 0.0.0.0:8545

  suppliers:
    - name: anvil
      type: http
      service_config:
        url: http://anvil:8547/
      proxy_names:
        - http-proxy
      hosts:
        - tcp://relayminers:8545