config:
  # TODO_TECHDEBT(@okdas): remove `signing_key_name` - which is currently present
  # for backwards-compatibity with the current helm-chart.
  signing_key_name: supplier3

  default_signing_key_names: [supplier3]
  suppliers:
    - service_id: anvil
      listen_url: http://0.0.0.0:8545
      service_config:
        backend_url: http://anvil:8547/
        publicly_exposed_endpoints:
          - relayminer3
    - service_id: ollama
      listen_url: http://0.0.0.0:8545
      service_config:
        backend_url: http://ollama:11434/
        publicly_exposed_endpoints:
          - relayminer3
