config:
  signing_key_name: supplier3
  suppliers:
    - service_id: anvil
      server_type: http
      service_config:
        backend_url: http://anvil:8547/
        publicly_exposed_endpoints:
        - tcp://relayminer3:8545
      listen_address: 0.0.0.0:8545
