config:
  signing_key_name: supplier3
  suppliers:
    - service_id: anvil
      type: http
      service_config:
        url: http://anvil:8547/
      proxy_names:
        - http-proxy
      hosts:
        - tcp://relayminer3:8545
