name: Telegram Broadcast New Release

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: "If true, only send to testing group"
        required: false
        type: boolean
        default: false

jobs:
  notify:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.prepare_message.outputs.message }}
    steps:
      - name: Get latest release
        id: get_release
        run: |
          RELEASE_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest")

          RELEASE_NAME=$(echo "$RELEASE_INFO" | jq -r '.name // "Unnamed Release"')
          RELEASE_URL=$(echo "$RELEASE_INFO" | jq -r '.html_url // ""')
          RELEASE_BODY=$(echo "$RELEASE_INFO" | jq -r '.body // ""')

          echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT
          echo "release_url=$RELEASE_URL" >> $GITHUB_OUTPUT
          echo "release_body<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Prepare release message
        id: prepare_message
        run: |
          RELEASE_NAME="${{ steps.get_release.outputs.release_name }}"
          RELEASE_URL="${{ steps.get_release.outputs.release_url }}"
          RELEASE_BODY="${{ steps.get_release.outputs.release_body }}"

          # Escape characters Telegram HTML mode can't handle
          escape_html() {
            echo "$1" | sed \
              -e 's/&/\&amp;/g' \
              -e 's/</\&lt;/g' \
              -e 's/>/\&gt;/g'
          }

          # Convert markdown to Telegram-compatible HTML
          convert_markdown_to_html() {
            echo "$1" | \
            sed -E 's/`([^`]+)`/<code>\1<\/code>/g' | \
            sed -E 's/\*\*([^*]+)\*\*/<b>\1<\/b>/g' | \
            sed -E 's/\*([^*]+)\*/<i>\1<\/i>/g' | \
            sed -E 's/\[([^\]]+)\]\(([^\)]+)\)/<a href="\2">\1<\/a>/g'
          }

          # Sanitize body
          SAFE_BODY=$(escape_html "$RELEASE_BODY")
          HTML_RELEASE_BODY=$(convert_markdown_to_html "$SAFE_BODY")

          # Fallback if body is empty
          if [ -z "$HTML_RELEASE_BODY" ]; then
            HTML_RELEASE_BODY="<i>No additional release notes provided.</i>"
          fi

          if [ "${{ inputs.test_mode }}" = "true" ]; then
            MESSAGE=$(printf "🧪 <b>TEST RELEASE NOTIFICATION</b> 🧪\n\n📣 The <b>%s</b> release is live! 📣\n<a href=\"%s\">View the full release here</a>\n\n%s" "$RELEASE_NAME" "$RELEASE_URL" "$HTML_RELEASE_BODY")
          else
            MESSAGE=$(printf "📣 The <b>%s</b> release is live! 📣\n<a href=\"%s\">View the full release here</a>\n\n%s" "$RELEASE_NAME" "$RELEASE_URL" "$HTML_RELEASE_BODY")
          fi

          echo "DEBUG: First 200 characters of MESSAGE:"
          echo "$MESSAGE" | head -c 200
          echo

          echo "message<<EOF" >> $GITHUB_OUTPUT
          echo "$MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  send-release:
    needs: notify
    uses: ./.github/workflows/telegram-send-message.yml
    with:
      message: ${{ needs.notify.outputs.message }}
      parse_mode: "HTML"
      test_mode: ${{ inputs.test_mode }}
