name: Telegram Broadcast New Release

### How to use this? ###
# 1. Finish the release procedure: https://dev.poktroll.com/develop/upgrades/release_procedure?_highlight=release
# 2. Set the latest release to latest and verify here: https://github.com/pokt-network/poktroll/releases/latest
# 3. Manually trigger the workflow by either:
#    - Clicking the "Run workflow" button here: https://github.com/pokt-network/poktroll/actions/workflows/telegram-notify-release.yml
#    - Or by running the following command in your terminal: $ gh workflow run telegram-notify-release.yml

### How to test / debug this? ###
# 1. Submit a new PR in a new branch that's modifying this file
# 2. Trigger the workflow by running the following command in your terminal: $ gh workflow run telegram-notify-release.yml --ref <BRANCH_NAME>
# 3. Verify the workflow worked by viewing the logs here: https://github.com/pokt-network/poktroll/actions/workflows/telegram-notify-release.yml
# 4. Check the output in the telegram bot group: https://web.telegram.org/k/#-2895286734

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: "If true, only send to testing group"
        required: false
        type: boolean
        default: false
  # Uncomment the lines below to automatically trigger on release publication
  # This is commented out to avoid premature notifications
  # release:
  #   types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    # Uncomment the line below when enabling automatic triggers
    # if: github.event.release.prerelease == false
    outputs:
      message: ${{ steps.prepare_message.outputs.message }}
    steps:
      - name: Get latest release
        id: get_release
        run: |
          # Get latest release info from GitHub API
          RELEASE_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest")

          # Extract release details and properly escape for GitHub Actions
          RELEASE_NAME=$(echo "$RELEASE_INFO" | jq -r '.name // "Unknown Release"')
          RELEASE_URL=$(echo "$RELEASE_INFO" | jq -r '.html_url // ""')

          echo "Latest release: $RELEASE_NAME"
          echo "Release URL: $RELEASE_URL"

          # Handle multiline release body properly
          echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT
          echo "release_url=$RELEASE_URL" >> $GITHUB_OUTPUT

          # Use a more unique delimiter to avoid conflicts
          echo "release_body<<RELEASE_BODY_DELIMITER" >> $GITHUB_OUTPUT
          echo "$RELEASE_INFO" | jq -r '.body // "No release notes available."' >> $GITHUB_OUTPUT
          echo "RELEASE_BODY_DELIMITER" >> $GITHUB_OUTPUT

      - name: Prepare release message
        id: prepare_message
        run: |
          # Safely construct message using printf to avoid command execution
          RELEASE_NAME="${{ steps.get_release.outputs.release_name }}"
          RELEASE_URL="${{ steps.get_release.outputs.release_url }}"

          # Read release body and escape it properly to prevent command execution
          # Use printf to safely handle content with special characters
          RELEASE_BODY=$(printf '%s' "${{ steps.get_release.outputs.release_body }}")

          # Function to safely convert markdown to HTML with proper escaping
          convert_to_safe_html() {
            # First, escape all HTML entities in the raw text
            local content=$(echo "$1" | \
              sed 's/&/\&amp;/g' | \
              sed 's/</\&lt;/g' | \
              sed 's/>/\&gt;/g' | \
              tr -d '\r')

            # Now convert markdown to HTML by replacing the escaped versions
            echo "$content" | \
              # Convert ## headers to <b>headers</b>
              sed 's/^## \(.*\)$/<b>\1<\/b>/g' | \
              sed 's/^### \(.*\)$/<b>\1<\/b>/g' | \
              # Convert **bold** to <b>bold</b>
              sed 's/\*\*\([^*]\+\)\*\*/<b>\1<\/b>/g' | \
              # Convert [text](url) links - this is tricky because we escaped < and >
              sed 's/\[\([^]]*\)\](\([^)]*\))/<a href="\2">\1<\/a>/g'
          }

          # Convert to safe HTML
          HTML_RELEASE_BODY=$(convert_to_safe_html "$RELEASE_BODY")

          # Debug: Print the processed values
          echo "DEBUG: RELEASE_NAME='$RELEASE_NAME'"
          echo "DEBUG: First 200 chars of HTML_RELEASE_BODY:"
          echo "$HTML_RELEASE_BODY" | head -c 200
          echo "..."

          # Create message with HTML formatting - escape the release name too
          ESCAPED_RELEASE_NAME=$(echo "$RELEASE_NAME" | sed 's/&/\&amp;/g')

          # Also escape the URL to be safe
          ESCAPED_RELEASE_URL=$(echo "$RELEASE_URL" | sed 's/&/\&amp;/g')

          # Create message with HTML formatting - escape the release name too
          ESCAPED_RELEASE_NAME=$(echo "$RELEASE_NAME" | sed 's/&/\&amp;/g' | sed 's/</\&lt;/g' | sed 's/>/\&gt;/g')

          if [ "${{ inputs.test_mode }}" = "true" ]; then
            MESSAGE=$(printf "🧪 <b>TEST RELEASE NOTIFICATION</b> 🧪\n\n📣 The <b>%s release is live!</b> 📣\n<a href=\"%s\">View the full release here</a>\n\n%s" "$ESCAPED_RELEASE_NAME" "$RELEASE_URL" "$HTML_RELEASE_BODY")
          else
            MESSAGE=$(printf "📣 The <b>%s release is live!</b> 📣\n<a href=\"%s\">View the full release here</a>\n\n%s" "$ESCAPED_RELEASE_NAME" "$RELEASE_URL" "$HTML_RELEASE_BODY")
          fi

          # Debug: Print the first 200 chars of the message
          echo "DEBUG: First 200 chars of MESSAGE:"
          echo "$MESSAGE" | head -c 200
          echo "..."

          # Use a unique delimiter that won't appear in release notes
          echo "message<<MESSAGE_CONTENT_DELIMITER" >> $GITHUB_OUTPUT
          echo "$MESSAGE" >> $GITHUB_OUTPUT
          echo "MESSAGE_CONTENT_DELIMITER" >> $GITHUB_OUTPUT

  send-release:
    needs: notify
    uses: ./.github/workflows/telegram-send-message.yml
    with:
      message: ${{ needs.notify.outputs.message }}
      parse_mode: "HTML"
      test_mode: ${{ inputs.test_mode }}
