name: Temp CI job

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  GKE_CLUSTER: protocol-us-central1
  GKE_ZONE: us-central1

jobs:
  id:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: "0" # Per https://github.com/ignite/cli/issues/1674#issuecomment-1144619147

      - name: Set up Cloud SDK
        if: contains(github.event.pull_request.labels.*.name, 'devnet-test-e2e')
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          service_account_key: ${{ secrets.GKE_PROTOCOL_US_CENTRAL }}
          project_id: ${{ secrets.GKE_PROTOCOL_PROJECT }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GKE_PROTOCOL_US_CENTRAL }}'

      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ secrets.GKE_PROTOCOL_PROJECT }}

      - name: Run E2E test job
        env:
          IMAGE_TAG: sha-${{ github.event.pull_request.head.sha || github.sha }}
          NAMESPACE: devnet-issue-${{ github.event.number }}
          JOB_NAME: e2e-test-${{ github.event.pull_request.head.sha || github.sha }}
        run: bash .github/workflows-helpers/run-e2e-test.sh