name: Temp CI job

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  GKE_CLUSTER: protocol-us-central1
  GKE_ZONE: us-central1

jobs:
  id:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: "0" # Per https://github.com/ignite/cli/issues/1674#issuecomment-1144619147

      - name: Set up Cloud SDK
        if: contains(github.event.pull_request.labels.*.name, 'devnet-test-e2e')
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          service_account_key: ${{ secrets.GKE_PROTOCOL_US_CENTRAL }}
          project_id: ${{ secrets.GKE_PROTOCOL_PROJECT }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GKE_PROTOCOL_US_CENTRAL }}'

      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ secrets.GKE_PROTOCOL_PROJECT }}

      - name: Ensure Sequencer Pod is Ready
        env:
          NAMESPACE: devnet-issue-${{ github.event.number }}
          IMAGE_SHA: sha-${{ github.event.pull_request.head.sha || github.sha }}
          PURPOSE_LABEL: sequencer
        run: |
          # Check if the pod with the matching image SHA and purpose is ready
          echo "Checking for ready sequencer pod with image SHA ${IMAGE_SHA}..."
          while : ; do
            # Get all pods with the matching purpose
            PODS_JSON=$(kubectl get pods -n ${NAMESPACE} -l pokt.network/purpose=${PURPOSE_LABEL} -o json)
            
            # Check if any pods are running and have the correct image SHA
            READY_POD=$(echo $PODS_JSON | jq -r ".items[] | select(.status.phase == \"Running\") | select(.spec.containers[].image | contains(\"${IMAGE_SHA}\")) | .metadata.name")

            if [[ -n "${READY_POD}" ]]; then
              echo "Ready pod found: ${READY_POD}"
              break
            else
              echo "No ready pod with the image SHA ${IMAGE_SHA} found. Waiting..."
              sleep 10
            fi
          done


      - name: Run E2E test job
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          NAMESPACE: devnet-issue-${{ github.event.number }}
          JOB_NAME: e2e-test-${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          envsubst < .github/workflows-helpers/run-e2e-test-job-template.yaml > job.yaml

          kubectl apply -f job.yaml
          
          # Wait for the pod to be created and be in a running state
          echo "Waiting for the pod to be in the running state..."
          while : ; do
            POD_NAME=$(kubectl get pods -n ${NAMESPACE} --selector=job-name=${JOB_NAME} -o jsonpath='{.items[0].metadata.name}')
            POD_STATUS=$(kubectl get pod ${POD_NAME} -n ${NAMESPACE} -o jsonpath='{.status.phase}')
            [[ "${POD_STATUS}" == "Running" ]] && break
            echo "Current pod status: ${POD_STATUS}"
            sleep 5
          done

          echo "Pod is running. Streaming logs..."
          # Stream the pod logs
          kubectl logs -f ${POD_NAME} -n ${NAMESPACE}

          # Check the job status after the logs finish streaming
          if ! kubectl wait --for=condition=complete --timeout=600s job/${JOB_NAME} -n ${NAMESPACE}; then
            echo "Job failed"

            kubectl delete job ${JOB_NAME} -n ${NAMESPACE}
            exit 1
          fi

          kubectl delete job ${JOB_NAME} -n ${NAMESPACE}
