# Names of the key (in the keyring) used to run the suppliers for.
# These keys must correspond to the operator addresses of the suppliers.
default_signing_key_names: [supplier1]

# Path to the SMT KV store.
smt_store_path: ":memory:" # OR ./path/to/smt_stores

# Prometheus exporter configuration
metrics:
  # Enable or disable the metrics exporter
  enabled: true
  # The address (host:port or just port) for the metrics exporter to listen on.
  addr: :9090

# Pprof endpoint configuration. More information:
# https://pkg.go.dev/github.com/google/pprof#section-readme
pprof:
  enabled: false
  addr: localhost:6060

# Ping server configuration to test the connectivity of every
# suppliers.[].service_config.backend_url
ping:
  enabled: false
  addr: localhost:8081

pocket_node:
  # Pocket node URL exposing the CometBFT JSON-RPC API.
  # Used by the Cosmos client SDK, event subscriptions, etc.
  # If unspecified, defaults to `tx_node_rpc_url`.
  query_node_rpc_url: tcp://pocket-validator:26657
  # Pocket node URL exposing the Cosmos gRPC service for querying purposes.
  query_node_grpc_url: tcp://pocket-validator:9090
  # Pocket node URL exposing the CometRPC service.
  tx_node_rpc_url: tcp://pocket-validator:9090

# Suppliers are different services offered on Pocket Network,
# proxied through Relay Miner.
suppliers:
  # The `service_id` of the service offered on the network.
  # Must match the Service.Id of the staked service.
  # Must be unique in the `suppliers` array.
  # Required.
  - service_id: ethereum
    listen_url: http://0.0.0.0:80
    # Configuration of the service offered through RelayMiner.
    service_config:
      # Backend URL is the endpoint that the RelayMiner proxies the requests to.
      # Also known as the data node or service node.
      # Required.
      backend_url: http://anvil.servicer:8545

      # Authentication for the service (HTTP Basic Auth).
      # Optional.
      authentication:
        username: user
        password: pwd

      # Authentication via a static header might be desirable for high-traffic services.
      # Example: If the service requires a header like `Authorization: Bearer <PASSWORD>`
      # Optional.
      headers: {}

      # ForwardPocketHeaders adds Pocket-specific headers from the relay metadata
      # to the HTTP request header.
      # Added headers will be:
      # - Pocket-Supplier
      # - Pocket-Service
      # - Pocket-Session-Id
      # - Pocket-Application
      # - Pocket-Session-Start-Height
      # - Pocket-Session-End-Height
      forward_pocket_headers: true

    # Listen url, usually `http://0.0.0.0:80` (all network interfaces, port `80`).
    # The scheme in the URL is required in order to infer the server type.
    # Multiple suppliers can share one listen address.
    # Required.

  # Example of exposing an ollama LLM endpoint.
  - service_id: ollama:mistral:7b
    listen_url: http://0.0.0.0:80
    service_config:
      backend_url: http://localhost:11434
      forward_pocket_headers: false

  # Example with different RPC type configurations for XRPL EVM
  - service_id: xrplevm
    listen_url: http://0.0.0.0:8545

    # Default service configuration (used when no specific RPC type matches)
    service_config:
      backend_url: http://xrplevm-node:8545
      forward_pocket_headers: true

    # RPC type specific configurations for different XRPL EVM endpoints
    rpc_type_service_configs:
      # JSON-RPC endpoints (Ethereum-compatible API)
      json_rpc:
        backend_url: http://xrplevm-node:8545
        headers:
          Authorization: "Bearer xrpl-api-key"
        forward_pocket_headers: true

      # REST API endpoints (Cosmos SDK REST for XRPL sidechain)
      rest:
        backend_url: http://xrplevm-node:1317
        authentication:
          username: xrpluser
          password: xrplpass
        forward_pocket_headers: true

      # CometBFT RPC endpoints (for consensus layer queries)
      comet_bft:
        backend_url: http://xrplevm-node:26657
        forward_pocket_headers: true

      # WebSocket endpoints (for real-time event streaming)
      websocket:
        backend_url: ws://xrplevm-node:8546
        forward_pocket_headers: false
