# DEVELOPER_TIP: Allows to run and attach to the relayminer process from VSCode.
# 1. Change `relayminers.count` to `0` in `localnet_config.yaml`
# 2. Apply the following configuration in VSCode's `launch.json`:
#
# {
#     "name": "Run/debug relayminer",
#     "type": "go",
#     "request": "launch",
#     "mode": "auto",
#     "program": "${workspaceFolder}/cmd/pocketd",
#     "args": [
#         "relayminer",
#         "--keyring-backend=test",
#         "--config=${workspaceFolder}/localnet/pocketd/config/relayminer_config_localnet_vscode.yaml",
#         "--home=${workspaceFolder}/localnet/pocketd"
#     ],
# },

default_signing_key_names: [supplier1]
default_request_timeout_seconds: 600
default_enable_eager_relay_request_validation: true
smt_store_path: smt_stores
metrics:
  enabled: true
  addr: :9070
pocket_node:
  query_node_rpc_url: tcp://localhost:26657
  query_node_grpc_url: tcp://localhost:9090
  tx_node_rpc_url: tcp://localhost:26657
mining_supervisor:
  queue_size: 2000
  workers: 8
  enqueue_timeout_ms: 50
  drop_policy: "drop-oldest"
  gauge_sample_interval_ms: 100
  drop_log_interval_ms: 5
suppliers:
  - service_id: anvil
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://localhost:8547
      forward_pocket_headers: false
  - service_id: anvilws
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: ws://localhost:8547
      forward_pocket_headers: false
  - service_id: ollama
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://localhost:11434/
      forward_pocket_headers: false
  - service_id: rest
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: http://rest:10000/
      forward_pocket_headers: false
  - service_id: static
    listen_url: http://0.0.0.0:8545
    enable_eager_relay_request_validation: false
    service_config:
      backend_url: http://localhost:8548/

pprof:
  enabled: false
  addr: localhost:6070
ping:
  enabled: false
  addr: localhost:8081
