owner_address: pokt1j6dun0x8eyq5mmsmq83zs3c2utt85q8478c89u
operator_address: pokt1j6dun0x8eyq5mmsmq83zs3c2utt85q8478c89u
stake_amount: 1000071upokt
services:
  - service_id: anvil
    endpoints:
      - publicly_exposed_url: http://relayminer3:8545
        rpc_type: JSON_RPC
  - service_id: anvilws
    endpoints:
      - publicly_exposed_url: ws://relayminer3:8545
        rpc_type: WEBSOCKET
